repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        exclude: ^docs/conf.py

  - repo: https://gitlab.com/yaq/yaq-traits
    rev: v2020.10.1
    hooks:
      - id: yaq-traits-check

default_language_version:
  python: python3.8
