repos:
  - repo: https://github.com/psf/black
    rev: 172c0a78facd8f938629f216c95507bbfeddfe5e
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: ^docs/conf.py

  - repo: https://gitlab.com/yaq/yaq-traits
    rev: c080196487526513394e4c70e7d206fe0977054c
    hooks:
      - id: yaq-traits-check

default_language_version:
  python: python3.8
